#

spring:
  cloud:
    gateway:
      routes:
        - id: teams
          uri: http://localhost:8083
          predicates:
            - Path=/Arcane/teams/**
        - id: marketplace
          uri: http://localhost:8089
          predicates:
            - Path=/api/products/**